# appveyor.yml
build: off
before_build:
- choco install pandoc
build_script:
- pandoc -o output.docx draft.txt
artifacts:
- path: output.docx
  name: output
deploy:
- provider: GitHub
  auth_token:
    secure: d/jFwo/lO0o59JZDJdkA7E3NgHvknKz9aSMz4gRLMLZ6CiWJOGOA3mDYuAtCAEPo
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME) 
  description: "ummm"
  artifact: output      
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true             